### ISSUE TITLE
Problems with the Plasma Rifle

### ISSUE THREAD

**Issue by Rapidgame7** [marrub--/Lithium#49]
![screenshot_doom_20170525_003211](https://cloud.githubusercontent.com/assets/14862618/26434871/ac15af56-40e1-11e7-9d4c-9f6620c912cd.png)
Upon picking up the Plasma Rifle, the game throws an ACS error about "Lith_lith_player_scoresound" and does not give the weapon.

![screenshot_doom_20170525_003628](https://cloud.githubusercontent.com/assets/14862618/26434966/392eb752-40e2-11e7-8264-1b07ec279b69.png)
The weapon name seems to be glitched too (two lines below berserk).

**Comment by Rapidgame7** [comment]
I believe this mod works better in QZDoom than GZDoom.
I went straight to map30 in QZDoom and the plasma rifle I picked up worked just fine.

**Comment by marrub--** [comment]
(duplicate issue)
