### ISSUE TITLE
Also this

### ISSUE THREAD

**Issue by Rapidgame7** [marrub--/Lithium#50]
![screenshot_doom_20170525_004335](https://cloud.githubusercontent.com/assets/14862618/26435130/567318d4-40e3-11e7-8e3e-db8e17eb4517.png)

**Comment by Rapidgame7** [comment]
As with the previous issue, I went straight to this map in QZDoom and the plasma rifle worked just fine with no problems.

**Comment by Rapidgame7** [comment]
Nevermind, it still happens in QZDoom.
I guess it has to do depending on the stuff you have collected previously?
Because if I can pick it up just fine when I go straight to a map with the plasma rifle, but I can't (and I get an error) when I'm playing legit, then it should have to do with what I collected/bought.
![screenshot_doom_20170526_125824](https://cloud.githubusercontent.com/assets/14862618/26502552/942206fa-4213-11e7-8405-f55c8d041470.png)
![screenshot_doom_20170526_125856](https://cloud.githubusercontent.com/assets/14862618/26502553/94222bb2-4213-11e7-86a1-37860081be0b.png)
![screenshot_doom_20170526_125924](https://cloud.githubusercontent.com/assets/14862618/26502554/9423a7bc-4213-11e7-9c61-e5c71ae633e9.png)

**Comment by marrub--** [comment]
This is a known bug, the string `PlasmaRifle` gets replaced randomly in versions of ZDoom past 2.8.1. I don't know why.

**Comment by Rapidgame7** [comment]
I understand that this can happen in outdated versions, but this is the latest stable version of GZDoom (around 3.0.0) and the latest stable version of QZDoom
Unless they use old ZDoom versions as their base, then I don't know

**Comment by marrub--** [comment]
Versions **past** ZDoom 2.8.1 don't work. The mod was developed entirely using that version, and it's unfortunately all I can support due to this bug.

**Comment by marrub--** [comment]
Closing because this was fixed.
