### ISSUE TITLE
Adrenaline Autoinjector timer doesn't pause when in menus using Extras

### ISSUE THREAD

**Issue by DarkPulse** [marrub--/Lithium#51]
Exactly as it says on the tin.

If you have the game and the Extras enabled, and your Adrenaline has fired off, simply screw around in the menus for the thirty seconds it takes to recharge.

Eventually, it will reactivate.

(Not sure if this applies without the Extras, but since the Extras is supposed to pause most things, it clearly is not pausing this.)

**Comment by marrub--** [comment]
Fixed in https://github.com/marrub--/Lithium/commit/b5aac12e8602ac29bbb98fa4cecd89d431a69757, thanks.
